# Generated by Django 5.0.1 on 2024-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_hospital_doctor_remove_hospital_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
