# Generated by Django 5.0.1 on 2024-01-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
